### ISSUE TITLE
Get ready for deprecating this repository

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/cmake-modules#1]
This repository used to be used by most `mk*` sub-libraries. Now most sub-libraries have been converted to using measurement-kit/mkbuild instead. Remaining libs:

- [x] github.com/measurement-kit/mkorchestra (see https://github.com/measurement-kit/mkorchestra/issues/6)

- [ ] github.com/measurement-kit/libndt (see https://github.com/measurement-kit/libndt/issues/91)

- [x] github.com/measurement-kit/mkudns (see https://github.com/measurement-kit/mkudns/issues/1)

When they will be converted, we can mark this repository as deprecated and freeze it.

**Comment by bassosimone** [comment]
Libdnt has not been converted yet. I already have code in https://github.com/measurement-kit/libndt/pull/108 for replacing cmake-modules. At this point it's fair to archive this repository, considering that there will be no further updates of the code.
